# Generated by Django 3.0.8 on 2021-06-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_booker', '0002_auto_20210611_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_guests',
            field=models.IntegerField(null=True),
        ),
    ]
