# Generated by Django 3.0.8 on 2021-06-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_booker', '0003_booking_total_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='advance_booking',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='max_guest',
        ),
    ]
